### ISSUE TITLE
project planning 

### ISSUE THREAD

**Issue by huydx** [huydx/mr-scheduler#2]
## Purpose
- App nơi mọi người có thể schedule hẹn hò **với số đông** một cách dễ dàng nhất
  - minimum step
  - great UI
## How

Bắt chước https://chouseisan.com/
## Detail
- [ ] Flow cũng bắt chước chouseisan?
- [ ] Giảm chức năng / thêm chức năng không?
- [ ] Minimum value product sẽ gồm có những chức năng gì ???
## Tasks

???

**Comment by huytd** [comment]
E nghĩ nên chia làm nhiều phase, rồi phase đầu tiên thì mình clone, phase 2 bắt đầu thêm chức năng vô :D

**Comment by karmiphuc** [comment]
My 2 cents: MVP thì chỉ cần làm đúng 1 chức năng mà anh HuyDX đã nói ở phần purpose. Quan trọng là mình làm tốt phần on-boarding và UX thì cứ theo network effect mà nó tự grow và tự đẻ ra chức năng nó thực sự cần.

> App nơi mọi người có thể schedule hẹn hò với số đông một cách dễ dàng nhất

---

ADMIN
- Input: Thông tin sơ về event, admin email, contact list (email-based), deadline.
- Output: List of unique event links.

USER
- Given: Event link (unique per email per event)
- Input: Opt-out những ngày không đi được (vì theo UX thì opt-in tốt hơn cho người dùng)
- Output: User stats

**Comment by huytd** [comment]
Đính chính xíu, trong app này tại hạ thiết nghĩ là chúng ta không nên dùng ADMIN và USER đó mà... :v Theo ý kiến của tại hạ thì, chúng ta nên dùng tên là HOLDER (Chủ xị) và ATTENDEE (Dân chơi)

**Comment by huydx** [comment]
https://chouseisan.com/s?h=6be6090eae98449997db7ec57351aacf
Đây là một ví dụ về một sự kiện của choseisan, về UX rất đơn giản không có admin gì cả, chỉ cần
- Tên event
- Các thời điểm có thể chọn (theo ngày/giờ)
- Memo

là có thể tạo được event.
Người nhận event có thể: 
- add thêm tên mình
- tick vào những thời điểm hợp lý với bản thân (với 3 lựa chọn là tròn, tam giác và x)

**Comment by karmiphuc** [comment]
@huytd: Gọi sao thì tùy tên ACTOR mình đặt thôi =]] Nghĩ không ra nên đặt là vậy, chứ thực ra auth-less thì tốt hơn. Kiểu CHUXI tạo xong thì sẽ có 1 unique link để vào quản lý và thêm contact chứ cần gì auth thêm. MVP cũng chỉ cho phép DANCHOI nhập 1 lần rồi thôi, chưa cho sửa đi.

Cơ mà ý kiến chủ quan là vậy. Cũng cần bàn thêm.

**Comment by huytd** [comment]
UI cho trang tạo event:

![screen shot 2016-04-24 at 9 04 08 pm](https://cloud.githubusercontent.com/assets/613943/14773553/2a49808c-0a60-11e6-8486-669f752dc5a3.png)

Download: 
[mrsch.zip](https://github.com/huydx/mr-scheduler/files/233883/mrsch.zip)
